# Generated by Django 5.2.7 on 2026-04-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='about',
            new_name='description',
        ),
    ]
