# Generated by Django 6.0.5 on 2026-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
